[package]
name = "survey_rs-1"
version = "0.1.0"
authors = ["Tanguy Maz√© <tmaze@student.42.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"termion" = "1.5.6"
"isatty" = "0.1.9"

